// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Victory$ReactTemplate = require("./Victory.bs.js");

var component = ReasonReact.statelessComponent("Page");

function make() {
  var newrecord = component.slice();
  newrecord[/* render */9] = (function () {
      var data = /* array */[
        {
          x: 1,
          y: 13000
        },
        {
          x: 2,
          y: 16500
        },
        {
          x: 3,
          y: 14250
        },
        {
          x: 4,
          y: 19000
        }
      ];
      console.log(data);
      return ReasonReact.element(/* None */0, /* None */0, Victory$ReactTemplate.VictoryBar[/* make */0](/* None */0, /* None */0, /* None */0, /* array */[]));
    });
  return newrecord;
}

exports.component = component;
exports.make = make;
/* component Not a pure module */
