// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as Victory from "victory";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Js_undefined from "bs-platform/lib/es6/js_undefined.js";

function make(data, children) {
  console.log(data);
  return ReasonReact.wrapJsForReason(Victory.VictoryBar, {
              data: Js_undefined.fromOption(data)
            }, children);
}

var VictoryBar = /* module */[/* make */make];

function make$1(colorScale, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryStack, {
              colorScale: colorScale
            }, children);
}

var VictoryStack = /* module */[/* make */make$1];

function make$2(domainPadding, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryChart, {
              domainPadding: domainPadding
            }, children);
}

var VictoryChart = /* module */[/* make */make$2];

function make$3(tickValues, tickFormat, dependentAxis, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryAxis, {
              tickValues: tickValues,
              tickFormat: tickFormat,
              dependentAxis: dependentAxis
            }, children);
}

var VictoryAxis = /* module */[/* make */make$3];

export {
  VictoryBar ,
  VictoryStack ,
  VictoryChart ,
  VictoryAxis ,
  
}
/* victory Not a pure module */
