// Generated by BUCKLESCRIPT VERSION 2.2.0, PLEASE EDIT WITH CARE
'use strict';

var Victory = require("victory");
var ReasonReact = require("reason-react/src/ReasonReact.js");

function make(data, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryBar, {
              data: data
            }, children);
}

var VictoryBar = /* module */[/* make */make];

function make$1(colorScale, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryStack, {
              colorScale: colorScale
            }, children);
}

var VictoryStack = /* module */[/* make */make$1];

function make$2(domainPadding, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryChart, {
              domainPadding: domainPadding
            }, children);
}

var VictoryChart = /* module */[/* make */make$2];

function make$3(tickValues, tickFormat, dependentAxis, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryAxis, {
              tickValues: tickValues,
              tickFormat: tickFormat,
              dependentAxis: dependentAxis
            }, children);
}

var VictoryAxis = /* module */[/* make */make$3];

exports.VictoryBar = VictoryBar;
exports.VictoryStack = VictoryStack;
exports.VictoryChart = VictoryChart;
exports.VictoryAxis = VictoryAxis;
/* victory Not a pure module */
