// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as Victory from "victory";
import * as ReasonReact from "reason-react/src/ReasonReact.js";
import * as Js_undefined from "bs-platform/lib/es6/js_undefined.js";

var VictoryTheme = /* module */[];

function make(data, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryBar, {
              data: Js_undefined.fromOption(data)
            }, children);
}

var VictoryBar = /* module */[/* make */make];

function make$1(colorScale, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryStack, {
              colorScale: Js_undefined.fromOption(colorScale)
            }, children);
}

var VictoryStack = /* module */[/* make */make$1];

function make$2(domainPadding, theme, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryChart, {
              domainPadding: Js_undefined.fromOption(domainPadding),
              theme: Js_undefined.fromOption(theme)
            }, children);
}

var VictoryChart = /* module */[/* make */make$2];

function make$3(tickValues, tickFormat, dependentAxis, children) {
  return ReasonReact.wrapJsForReason(Victory.VictoryAxis, {
              tickValues: Js_undefined.fromOption(tickValues),
              tickFormat: Js_undefined.fromOption(tickFormat),
              dependentAxis: Js_undefined.fromOption(dependentAxis)
            }, children);
}

var VictoryAxis = /* module */[/* make */make$3];

function make$4(animate, data, $staropt$star, children) {
  var interpolation = $staropt$star ? $staropt$star[0] : "linear";
  return ReasonReact.wrapJsForReason(Victory.VictoryArea, {
              animate: Js_undefined.fromOption(animate),
              data: Js_undefined.fromOption(data),
              interpolation: interpolation
            }, children);
}

var VictoryArea = /* module */[/* make */make$4];

export {
  VictoryTheme ,
  VictoryBar ,
  VictoryStack ,
  VictoryChart ,
  VictoryAxis ,
  VictoryArea ,
  
}
/* victory Not a pure module */
